package org.harley.reman.interfaz.interfaces;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.harley.reman.interfaz.utilitario.ToolsInterface;
import org.harley.reman.sistema.Historico;
import org.harley.reman.sistema.Sistema;

public class VOERestaurar extends JDialog {

    Sistema sysReman;
    int tipLib;
    String codEle;
    ArrayList<Historico> historic;
    boolean flagOk;
    boolean flagLoadOk;

    public VOERestaurar(JFrame padre, Sistema sysReman, String codEle, int tipLib) {
        super(padre, true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.sysReman = sysReman;
        this.tipLib = tipLib;
        this.codEle = codEle;
        
        switch (tipLib) {
            case Sistema.LIB_EDU:
                txtTitle.setText("EDUCCION: " + codEle);
                break;

            case Sistema.LIB_ELI:
                txtTitle.setText("ELICITACION: " + codEle);
                break;

            case Sistema.LIB_ESP:
                txtTitle.setText("ESPECIFICACION: " + codEle);
                break;

            case Sistema.LIB_RNF:
                txtTitle.setText("REQ NO FUNCIONAL: " + codEle);
                break;

            default:
                txtTitle.setText("NONE DOC: " + codEle);
                break;
        }

        try {
            historic = sysReman.getHist(tipLib, codEle);
            ToolsInterface.putJTableHistorico(JTVersion, historic);
            flagLoadOk = true;
        } catch (Exception e) {
            flagLoadOk = false;
        }

    }

    public boolean getLoadIsCorrect() {
        return flagLoadOk;
    }
    
    public boolean versionSuccessful() {
        return flagOk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnVGuardar = new javax.swing.JButton();
        btnVCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTVersion = new javax.swing.JTable();
        txtTitle = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Restaurar");
        setResizable(false);

        btnVGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVGuardar.setText("Restaurar");
        btnVGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVGuardarActionPerformed(evt);
            }
        });

        btnVCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVCancelar.setText("Cancelar");
        btnVCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVCancelarActionPerformed(evt);
            }
        });

        JTVersion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTVersion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Versión", "Fecha", "Autor", "Razon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTVersion);

        txtTitle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTitle.setText("title");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(btnVCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtTitle)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(txtTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVCancelar))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVCancelarActionPerformed

    private void btnVGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVGuardarActionPerformed
        int numRow = JTVersion.getSelectedRow();
        String version;
        if (numRow != -1) {
            int resp = JOptionPane.showConfirmDialog(null, "Se perdera toda la informacion actual del documento a restaurar!", "Alerta!", JOptionPane.YES_NO_OPTION);
            if (resp == 0) {
                version = JTVersion.getValueAt(numRow, 0).toString();
                switch (tipLib) {
                    case Sistema.LIB_EDU:
                        sysReman.restaurarVersionEduccion(version, codEle);
                        break;

                    case Sistema.LIB_ELI:
                        sysReman.restaurarVersionElicitacion(version, codEle);
                        break;

                    case Sistema.LIB_ESP:
                        sysReman.restaurarVersionEspecificacion(version, codEle);
                        break;

                    case Sistema.LIB_RNF:
                        //sysReman.restaurarVersionReqNoFuncional(version, codEle);
                        break; 
                }
                ToolsInterface.msjInfo(this, "Operacion Exitosa", "Se recupero la version: " + version);
                flagOk = true;
                this.dispose();
            }

        } else {
            ToolsInterface.msjError(this, "Seleccione una version!");
        }


    }//GEN-LAST:event_btnVGuardarActionPerformed

    public static final int EDU = 0;
    public static final int ELI = 1;
    public static final int ESP = 2;
    public static final int RNF = 3;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTVersion;
    private javax.swing.JButton btnVCancelar;
    private javax.swing.JButton btnVGuardar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel txtTitle;
    // End of variables declaration//GEN-END:variables
}
