package org.harley.reman.interfaz.interfaces;

import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.harley.reman.interfaz.utilitario.ToolsInterface;
import org.harley.reman.sistema.Sistema;

/**
 *
 * @author Joel Mendoza
 */
public class VOExportar extends JDialog {

    Sistema sysReman;
    String direccion;
    String nombre;

    public VOExportar(JFrame padre, Sistema sysReman) {
        super(padre, true);
        initComponents();
        this.setLocationRelativeTo(null);

        this.sysReman = sysReman;
        direccion = "";
        nombre = "";

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ExportarFile = new javax.swing.JFileChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtENombre = new javax.swing.JTextField();
        cmbELibro = new javax.swing.JComboBox();
        btnECancelar = new javax.swing.JButton();
        btnEExportar = new javax.swing.JButton();
        btnEFileChooser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Exportar");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nombre del Documento");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Exportar");

        txtENombre.setEditable(false);
        txtENombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbELibro.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmbELibro.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libro Educción", "Libro Elicitación", "Libro Especificación", "Libro Req no Funcional", "Libro Organización", "Libro Actores" }));

        btnECancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnECancelar.setText("Cancelar");
        btnECancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnECancelarActionPerformed(evt);
            }
        });

        btnEExportar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEExportar.setText("Exportar");
        btnEExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEExportarActionPerformed(evt);
            }
        });

        btnEFileChooser.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnEFileChooser.setText("...");
        btnEFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEFileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 39, Short.MAX_VALUE)
                        .addComponent(btnECancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtENombre)
                        .addGap(18, 18, 18)
                        .addComponent(btnEFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cmbELibro, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(79, 79, 79))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbELibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnECancelar)
                    .addComponent(btnEExportar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEExportarActionPerformed
        if (direccion.equals("") || nombre.equals("")) {
            ToolsInterface.msjError(this, "Seleccione un ruta para exportar el libro");
        } else {
            if (!sysReman.exportarLibro(cmbELibro.getSelectedIndex(), direccion, nombre)) {
                ToolsInterface.msjError(this, "Error al cargar los datos del libro, reviselos antes de continuar la operacion!");
            } else {
                this.dispose();
            }
        }


    }//GEN-LAST:event_btnEExportarActionPerformed

    private void btnECancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnECancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnECancelarActionPerformed

    private void btnEFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEFileChooserActionPerformed
        int opt = ExportarFile.showSaveDialog(this);

        if (opt == JFileChooser.APPROVE_OPTION) {
            direccion = ExportarFile.getSelectedFile().getParent().trim();
            nombre = ExportarFile.getSelectedFile().getName().trim();
            nombre = ToolsInterface.addExtensionPdf(nombre);
            if (nombre.equals("error")) {
                ToolsInterface.msjError(this, "Error con el nombre del archivo, intentelo nuevamente!");
            } else {
                txtENombre.setText(direccion + "\\" + nombre + ".pdf");
            }
        }
    }//GEN-LAST:event_btnEFileChooserActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser ExportarFile;
    private javax.swing.JButton btnECancelar;
    private javax.swing.JButton btnEExportar;
    private javax.swing.JButton btnEFileChooser;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cmbELibro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtENombre;
    // End of variables declaration//GEN-END:variables
}
