/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.harley.reman.interfaz.interfaces;

import java.awt.event.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.TreePath;
import org.harley.reman.interfaz.utilitario.ToolsInterface;
import org.harley.reman.sistema.Sistema;

/**
 *
 * @author User
 */
public class VTEduccion extends javax.swing.JInternalFrame {

    Sistema sysReman;
    TreePath dirTree;
    JFrame padre;
    MouseListener ml = new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e) {
            // Se obtiene el path para esa fila. Con el path podemos obtener
            // los nodos.
            if (e.getButton() == MouseEvent.BUTTON3) {
                dirTree = treeEdu.getPathForLocation(e.getX(), e.getY());
                treeEdu.setSelectionPath(dirTree);
                if (dirTree != null) {
                    switch (dirTree.getLastPathComponent().toString()) {
                        case "Documento de Educción":
                            break;
                        case "Educción":
                            menuDocEdu.show(e.getComponent(), e.getX(), e.getY() + 10);
                            break;
                        default:
                            menuEdu.show(e.getComponent(), e.getX(), e.getY() + 10);
                            break;
                    }
                }
            }
        }
    };

    public VTEduccion(JFrame padre, Sistema sysReman, JTree tree) {
        initComponents();
        this.padre = padre;
        this.sysReman = sysReman;
        treeEdu.setModel(tree.getModel());
        treeEdu.addMouseListener(ml);
    }

    public VTEduccion(JFrame padre, Sistema sysReman) {
        initComponents();
        this.padre = padre;
        this.sysReman = sysReman;
        treeEdu.addMouseListener(ml);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuDocEdu = new javax.swing.JPopupMenu();
        menuDocEduItem1 = new javax.swing.JMenuItem();
        menuEdu = new javax.swing.JPopupMenu();
        menuEduItem1 = new javax.swing.JMenuItem();
        menuEduItem2 = new javax.swing.JMenuItem();
        menuEduItem3 = new javax.swing.JMenuItem();
        scrollTree = new javax.swing.JScrollPane();
        treeEdu = new javax.swing.JTree();

        menuDocEduItem1.setText("Crear Educción");
        menuDocEduItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDocEduItem1ActionPerformed(evt);
            }
        });
        menuDocEdu.add(menuDocEduItem1);

        menuEduItem1.setText("Modificar");
        menuEduItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEduItem1ActionPerformed(evt);
            }
        });
        menuEdu.add(menuEduItem1);

        menuEduItem2.setText("Eliminar");
        menuEduItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEduItem2ActionPerformed(evt);
            }
        });
        menuEdu.add(menuEduItem2);

        menuEduItem3.setText("Restaurar");
        menuEduItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEduItem3ActionPerformed(evt);
            }
        });
        menuEdu.add(menuEduItem3);

        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(250, 322));

        treeEdu.setBackground(new java.awt.Color(217, 221, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Documento de la Educción");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Educción");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("EDU 0001");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeEdu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        scrollTree.setViewportView(treeEdu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTree, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTree, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuDocEduItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDocEduItem1ActionPerformed
        //NUEVA EDUCCION
        VEduccion VEdu = new VEduccion(padre, sysReman);
        if (VEdu.getLoadIsCorrect()) {
            VEdu.setVisible(true);
        } else {
            ToolsInterface.msjError(padre, "Error al cargar los actores del proyecto!");
        }
        if (VEdu.createSuccessful()) {
            actualizarJTree();
        }       
    }//GEN-LAST:event_menuDocEduItem1ActionPerformed

    private void menuEduItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEduItem1ActionPerformed
        //MODIFICAR EDUCCION
        String path = dirTree.getLastPathComponent().toString();
        VMEduccion VEdu = new VMEduccion(padre, sysReman, path);
        if (VEdu.getLoadIsCorrect()) {
            VEdu.setVisible(true);
        } else {
            ToolsInterface.msjError(padre, "Error al cargar los datos de los actores!");
        }

    }//GEN-LAST:event_menuEduItem1ActionPerformed

    private void menuEduItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEduItem2ActionPerformed
        //ELIMINAR EDUCCION
        String path;
        int resp = JOptionPane.showConfirmDialog(null, "Eliminar Educción", "Alerta!", JOptionPane.YES_NO_OPTION);
        if (resp == 1) {
            path = dirTree.getLastPathComponent().toString();
            sysReman.eliminarEduccion(path);
            actualizarJTree();
            ToolsInterface.msjInfo(padre, "Eliminacion Exitosa", "Se elimino correctamente la Educcion: " + path);
        }     
    }//GEN-LAST:event_menuEduItem2ActionPerformed

    private void menuEduItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEduItem3ActionPerformed
        //RESTAURAR
    }//GEN-LAST:event_menuEduItem3ActionPerformed

    public void actualizarJTree() {
        JTree Tmodel = ToolsInterface.generateJTreeBook("Documento de Educción", "Educción", sysReman.getDirPrincipal() + "\\src\\edu");
        treeEdu.setModel(Tmodel.getModel());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPopupMenu menuDocEdu;
    private javax.swing.JMenuItem menuDocEduItem1;
    private javax.swing.JPopupMenu menuEdu;
    private javax.swing.JMenuItem menuEduItem1;
    private javax.swing.JMenuItem menuEduItem2;
    private javax.swing.JMenuItem menuEduItem3;
    private javax.swing.JScrollPane scrollTree;
    private javax.swing.JTree treeEdu;
    // End of variables declaration//GEN-END:variables
}
