/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.harley.reman.interfaz.interfaces;
import java.awt.event.*;
import javax.swing.tree.TreePath;
import javax.swing.JOptionPane;
/**
 *
 * @author User
 */
public class VTOrganizacion extends javax.swing.JInternalFrame {

    /**
     * Creates new form VTOrganizacion
     */
    public VTOrganizacion() {
        initComponents();
        trOrganizacion.addMouseListener(ml);
        
    }
    MouseListener ml = new MouseAdapter(){
        public void mouseClicked(MouseEvent e) {
         // Se obtiene el path para esa fila. Con el path podemos obtener
         // los nodos.
            if (e.getButton()==3){
                TreePath selPath = trOrganizacion.getPathForLocation(e.getX(), e.getY());
                trOrganizacion.setSelectionPath(selPath);
                String node = selPath.getLastPathComponent().toString();
                if(selPath !=null){
                    if(node.equals("Documentos de la Organización")|| node.equals("Autor") || node.equals("Fuente")){
                    }
                    else if(node.equals("Organización")){
                       menu1.show(e.getComponent(), e.getX(),e.getY()+10);
                    }
                    else if(node.equals("Actores")){
                       menu3.show(e.getComponent(), e.getX(),e.getY()+10);
                    }
                    else{
                       menu2.show(e.getComponent(), e.getX(),e.getY()+10);
                    }
                }
            }
        }
    };
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu1 = new javax.swing.JPopupMenu();
        jMenuItem = new javax.swing.JMenuItem();
        menu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menu3 = new javax.swing.JPopupMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        trOrganizacion = new javax.swing.JTree();

        jMenuItem.setText("Crear Organización");
        jMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemActionPerformed(evt);
            }
        });
        menu1.add(jMenuItem);

        jMenuItem1.setText("Modificar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menu2.add(jMenuItem1);

        jMenuItem2.setText("Eliminar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        menu2.add(jMenuItem2);

        jMenuItem5.setText("Crear Autor");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menu3.add(jMenuItem5);

        jMenuItem4.setText("Crear Fuente");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        menu3.add(jMenuItem4);

        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(250, 322));

        trOrganizacion.setBackground(new java.awt.Color(217, 221, 255));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Documentos de la Organización");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Organización");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("ORG - 01");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Actores");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Autor");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("AU - 01");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Fuente");
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("FU - 01");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        trOrganizacion.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trOrganizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(trOrganizacion, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here: MODIFICAR
        
        TreePath selPath = trOrganizacion.getSelectionPath();
        String parent = selPath.getParentPath().getLastPathComponent().toString();
        
        if ( parent.equals("Organización")){
            VOrganizacion modOrganizacion = new VOrganizacion();
            modOrganizacion.setVisible(true);
        }
        else if( parent.equals("Autor")){
            VActor modActor = new VActor();
            modActor.setVisible(true);
        }
        else{
            VFuente modFuente = new VFuente();
            modFuente.setVisible(true);
        }
            
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here: ELIMINAR
        TreePath selPath = trOrganizacion.getSelectionPath();
        String parent = selPath.getParentPath().getLastPathComponent().toString();
        
        if ( parent.equals("Organización")){
            int resp = JOptionPane.showConfirmDialog(null, "Eliminar Organización", "Alerta!", JOptionPane.YES_NO_OPTION);
            System.out.println("Eliminare una fuente");
        }
        else if( parent.equals("Autor")){
            int resp = JOptionPane.showConfirmDialog(null, "Eliminar Autor", "Alerta!", JOptionPane.YES_NO_OPTION);
        }
        else{
            int resp = JOptionPane.showConfirmDialog(null, "Eliminar Fuente", "Alerta!", JOptionPane.YES_NO_OPTION);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemActionPerformed
        // TODO add your handling code here:
        VOrganizacion VOrganiza = new VOrganizacion();
        VOrganiza.setVisible(true);
    }//GEN-LAST:event_jMenuItemActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        VActor vautor = new VActor();
        vautor.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        VFuente vfuente = new VFuente();
        vfuente.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu menu1;
    private javax.swing.JPopupMenu menu2;
    private javax.swing.JPopupMenu menu3;
    private javax.swing.JTree trOrganizacion;
    // End of variables declaration//GEN-END:variables
}
