package org.harley.reman.interfaz.interfaces;

import java.util.ArrayList;
import javax.swing.JDialog;
import javax.swing.JFrame;
import org.harley.reman.interfaz.utilitario.ToolsInterface;
import org.harley.reman.sistema.Historico;
import org.harley.reman.sistema.Sistema;
import org.harley.reman.sistema.ToolsSystem;

public class VVersionar extends JDialog {

    Sistema sysReman;
    ArrayList<Historico> libEdu;
    ArrayList<Historico> libEli;
    ArrayList<Historico> libEsp;
    ArrayList<Historico> libRnf;
    boolean flagLoadOk;
    boolean flagOk;

    public VVersionar(JFrame padre, Sistema sysReman) {
        super(padre, true);
        initComponents();
        this.setLocationRelativeTo(null);
        this.sysReman = sysReman;

        libEdu = sysReman.getHistLibEdu();
        libEli = sysReman.getHistLibEli();
        libEsp = sysReman.getHistLibEsp();
        libRnf = sysReman.getHistLibRnf();

        try {
            ToolsInterface.addItems2JComboBox(cmbVAutor, sysReman.getEspecialistaNombres());
            flagLoadOk = true;
        } catch (Exception e) {
            flagLoadOk = false;
        }

        try {
            ToolsInterface.putJTableHistorico(JTVersion, libEdu);
        } catch (Exception e) {
            //ToolsInterface.msjError(this, "- No se encontro historicos de libros de educcion.");
        }

    }

    public boolean getLoadIsCorrect() {
        return flagLoadOk && cmbVAutor.getItemCount() != 0;
    }

    public boolean versionSuccessful() {
        return flagOk;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtVVersion = new javax.swing.JTextField();
        cmbVAutor = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtRzcam = new javax.swing.JTextArea();
        dtEDFecha = new datechooser.beans.DateChooserCombo();
        btnVGuardar = new javax.swing.JButton();
        btnVCancelar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTVersion = new javax.swing.JTable();
        cmblib = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Versionar");
        setResizable(false);

        jLayeredPane3.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de la Versión"));
        jLayeredPane3.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Versión");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Fecha");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Autor");

        txtVVersion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        cmbVAutor.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Razon");

        txtRzcam.setColumns(20);
        txtRzcam.setRows(5);
        jScrollPane1.setViewportView(txtRzcam);

        dtEDFecha.setEnabled(false);

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtVVersion)
                    .addComponent(cmbVAutor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(dtEDFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVVersion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dtEDFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbVAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 99, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jLayeredPane3.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(txtVVersion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(cmbVAutor, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane3.setLayer(dtEDFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnVGuardar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVGuardar.setText("Versionar");
        btnVGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVGuardarActionPerformed(evt);
            }
        });

        btnVCancelar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnVCancelar.setText("Cancelar");
        btnVCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVCancelarActionPerformed(evt);
            }
        });

        JTVersion.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        JTVersion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Versión", "Fecha", "Autor", "Razon"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(JTVersion);

        cmblib.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cmblib.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Libro Educción", "Libro Elicitación", "Libro Especificación", "Libro Req no Funcional" }));
        cmblib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmblibActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Libro a Versionar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addComponent(btnVCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addComponent(jLayeredPane3)
                    .addComponent(cmblib, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(cmblib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLayeredPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVGuardar)
                            .addComponent(btnVCancelar))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Datos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVCancelarActionPerformed

    private void btnVGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVGuardarActionPerformed
        String version = txtVVersion.getText().trim();
        String fecha = dtEDFecha.getText().trim();
        String autor = (String) cmbVAutor.getSelectedItem();
        String rzcam = txtRzcam.getText();
        int select = cmblib.getSelectedIndex();
        String lastVersion = "0.1";
        try {
            switch (select) {
                case Sistema.LIB_EDU:
                    lastVersion = libEdu.get(libEdu.size() - 1).getVersion();
                    break;
                case Sistema.LIB_ELI:
                    lastVersion = libEli.get(libEli.size() - 1).getVersion();
                    break;
                case Sistema.LIB_ESP:
                    lastVersion = libEsp.get(libEsp.size() - 1).getVersion();
                    break;
                case Sistema.LIB_RNF:
                    lastVersion = libRnf.get(libRnf.size() - 1).getVersion();
                    break;
            }
        } catch (Exception e) {
        }

        if (ToolsInterface.verificarVersion(version)) {
            if (ToolsSystem.CompararVersiones(version, lastVersion)) {
                sysReman.versionarLibro(select, version, fecha, rzcam, autor);
                ToolsInterface.msjInfo(this, "Operacion Exitosa", "Se versiono correctamente");
                actualizarJTable(select);
            } else {
                ToolsInterface.msjError(this, "Utilice una version superior a la ultima desarrollada!");
            }
        } else {
            ToolsInterface.msjError(this, "Escriba correctamente la version!");
        }


    }//GEN-LAST:event_btnVGuardarActionPerformed

    private void actualizarJTable(int select) {
        switch (select) {
            case Sistema.LIB_EDU:
                libEdu = sysReman.getHistLibEdu();
                try {
                    ToolsInterface.putJTableHistorico(JTVersion, libEdu);
                } catch (Exception e) {
                }

                break;
            case Sistema.LIB_ELI:
                libEli = sysReman.getHistLibEli();
                try {
                    ToolsInterface.putJTableHistorico(JTVersion, libEli);
                } catch (Exception e) {
                }

                break;
            case Sistema.LIB_ESP:
                libEsp = sysReman.getHistLibEsp();
                try {
                    ToolsInterface.putJTableHistorico(JTVersion, libEsp);
                } catch (Exception e) {
                }

                break;
            case Sistema.LIB_RNF:
                libRnf = sysReman.getHistLibRnf();
                try {
                    ToolsInterface.putJTableHistorico(JTVersion, libRnf);
                } catch (Exception e) {
                }
                break;
        }
    }

    private void cmblibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmblibActionPerformed
        switch (cmblib.getSelectedIndex()) {
            case EDU:
                try {
                    ToolsInterface.putJTableHistorico(JTVersion, libEdu);
                } catch (Exception e) {
                    //ToolsInterface.msjError(this, "- No se encontro historicos de libros de educcion.");
                }
                break;
            case ELI:
                try {
                    ToolsInterface.putJTableHistorico(JTVersion, libEli);
                } catch (Exception e) {
                    //ToolsInterface.msjError(this, "- No se encontro historicos de libros de elicitacion.");
                }
                break;
            case ESP:
                try {
                    ToolsInterface.putJTableHistorico(JTVersion, libEsp);
                } catch (Exception e) {
                    //ToolsInterface.msjError(this, "- No se encontro historicos de libros de especificacion de req.");
                }
                break;
            case RNF:
                try {
                    ToolsInterface.putJTableHistorico(JTVersion, libRnf);
                } catch (Exception e) {
                    //ToolsInterface.msjError(this, "- No se encontro historicos de libros de req no funcionales.");
                }
                break;
        }
    }//GEN-LAST:event_cmblibActionPerformed

    public static final int EDU = 0;
    public static final int ELI = 1;
    public static final int ESP = 2;
    public static final int RNF = 3;


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTVersion;
    private javax.swing.JButton btnVCancelar;
    private javax.swing.JButton btnVGuardar;
    private javax.swing.JComboBox cmbVAutor;
    private javax.swing.JComboBox cmblib;
    private datechooser.beans.DateChooserCombo dtEDFecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtRzcam;
    private javax.swing.JTextField txtVVersion;
    // End of variables declaration//GEN-END:variables
}
